travis:
  secure:
    BINSTAR_TOKEN: LPPlUdnRUtK65QE06tuTHlqndBb8jlXJ8cNyn0xbPQpVD2r6dbg/efvxP7itfwABVAYV7TcejSeQaYCySwj4zShX1yaFpSGi1b3dV45pwx/a0yAjrrSykEXSO68US5b7BffnrlalBcO99OosNJc/TuioH0o8hFLU4QkFURh5+wRdqMcNZYDDmAOe7OPzaW0C9g0JFz9mxmXts54AxJHA1j6MtqovKnSzHjCO1SH13HXci6AYWeotTsYZvkMFTqWPTDkB4ltYhy8ukKUNTajm3uBhHB4wNb5c4kBasSrqRr3Q28aitjabwB3YoSS8dBKXj3iX9EtYt9gBXUadKzxzEaUTEzQSIixIqZmrWlmKN2Hq3XIZSAX5IvdFtZZ5XbGrACP5LXDf6AFABu0A46+0ATekD3CiPoA8EiM5uzWWjqTnZJ7Y/lVajIHeNN7NWeQ14mQeyxO1vhpB8/rnB/9ugUXVHvlfOtg9bL2ZKg4nbVrCoKXgGkTGM3RtohvBFyFkMWSTbwwGh57Ja9IjQbQ4taU0es8oxWnFa9hzEfRkjuQQfYc6Jg+e6isjARxOgYm6xY2YM9NG3JQ+scZfdUQ1Lqy0a1BWbdJGJeGBLY5rANQHgf22l7ygb9jbQcJvKcGLN4My9E4K5h2QcWfpKDtD4FcoeUcU25e4w/2DyEqyvH0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
